management:
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: ["*"]
      path-mapping:
        prometheus: metrics
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true
  metrics:
    enable:
      jvm: true
      logback: false
      process:
        files: false
        uptime: true
        cpu: true
      system:
        cpu: false
  server:
    port: 9090
spring:
  profiles:
    active: production
  application:
    name: "RentalDemo Service"
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: rental-service
      enable-auto-commit: false
      auto-offset-reset: earliest
      value-deserializer: com.sixt.rental.messagesubscriber.integration.kafka.serde.ProtobufDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual_immediate
rental-service:
  topics:
    event-listener: "book-lifecycle-events"